** Título: ProjetoEngenharia-STC-3D-SimuladorDeTransferenciaDeCalor-3D
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-STC-3D-SimuladorDeTransferenciaDeCalor-3D
- Resumo:
  - Projeto de engenharia - Simulador de condução térmica em objetos 3D com perfis genéricos.
  - O seguinte projeto de engenharia deve simular a difusão térmica de qualquer objeto tridimensional, onde o usuário desenha a superfície de alguns perfis e escolhe as temperaturas e suas propriedades termofísicas.
  - A equação do Calor será modelada por diferenças finitas pelo modelo BTCS, utilizando fronteiras de Neumann, e a programação utilizará paralelismo e multithreading para acelerar as simulações.
  - No quesito prático, o usuário poderá desenhar a superfície a ser simulada, escolher sua temperatura, propriedades termofísicas e se é fonte/sumidouro ou não. Também terá a liberdade de escolher um ponto para analisar os gráficos da evolução térmica no tempo e espaço, salvar as superfícies dos perfis e carregar essas camadas com todas as suas propriedades e modificá-las. Por fim, o projeto será utilizado para estudar a injeção de calor em reservatórios 2D e 3D, e avaliar a distribuição da temperatura ao longo do tempo no reservatório.
  - Nota: Também foi o TCC do aluno Nikolas.
- Área:
  - Transferência de calor.
- Autor:
  - Nikolas Almeida Pinto.
  - Publicação:
    - [[https://github.com/ldsc/ProjetoEngenharia-STC-3D-SimuladorDeTransferenciaDeCalor-3D/blob/master/doc/ManualTecnico/TCC-NikolasAlmeidaPinto.pdf][TCC]] 
    - [[https://github.com/ldsc/ProjetoEngenharia-STC-3D-SimuladorDeTransferenciaDeCalor-3D/blob/master/doc/ManualTecnico/Apresentacao_Nicholas_TCC2.pptx][Apresentacao]]

 
* Versão:
- 1.0.

* Data:
- 2021.

* Autor de Contato:
- André Duarte Bueno
- [[mailto:andreduartebueno@gmail.com][andreduartebueno@gmail.com]]
- [[mailto:bueno@lenep.uenf.br][bueno@lenep.uenf.br]]
- Nikolas Almeida Pinto
- [[mailto:nicholaspinto@lenep.uenf.br][nicholaspinto@lenep.uenf.br]]
